CREATE TABLE IF NOT EXISTS `weibo_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `screen_name` varchar(128) NOT NULL,
  `name` varchar(128) CHARACTER SET gbk NOT NULL,
  `province` int(11) NOT NULL,
  `city` int(11) NOT NULL,
  `location` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(256) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(128) CHARACTER SET latin1 NOT NULL,
  `profile_image_url` varchar(128) CHARACTER SET latin1 NOT NULL,
  `domain` varchar(128) CHARACTER SET latin1 NOT NULL,
  `gender` varchar(2) CHARACTER SET latin1 NOT NULL,
  `followers_count` int(11) NOT NULL,
  `friends_count` int(11) NOT NULL,
  `statuses_count` int(11) NOT NULL,
  `favourites_count` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `following` int(11) DEFAULT NULL,
  `allow_all_act_msg` int(11) NOT NULL,
  `geo_enabled` int(11) NOT NULL,
  `verified` int(11) NOT NULL,
  `status_id` int(11) DEFAULT NULL,
  `clicks` int(11) NOT NULL DEFAULT '0',
  `likes` int(11) NOT NULL DEFAULT '0',
  `dislikes` int(11) NOT NULL DEFAULT '0',
  `lastvotetime` datetime DEFAULT NULL,
  `weeklyclicks` int(11) NOT NULL DEFAULT '0',
  `weeklylikes` int(11) NOT NULL DEFAULT '0',
  `weeklydislikes` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid` (`uid`)
)